name: Exam Bot Deploy

on:
  push:
    branches:
     - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
      - run: npm run build
      - run: ls
      - run: cp dist/bundle.js index.js
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Create Archive
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r ./bundle.zip ./index.js

      - name: Deploy Lambda
        run: aws lambda update-function-code --function-name ExamBot --zip-file fileb://bundle.zip
      
      - name: Deploy bundle to S3
        run: aws s3 cp bundle.zip s3://test.exams.ng/bundle.zip